"""empty message

Revision ID: 112a9532cc3d
Revises: ebf8fb010cba
Create Date: 2019-10-03 18:58:35.429441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112a9532cc3d'
down_revision = 'ebf8fb010cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('output')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('output',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
